### ISSUE TITLE
Failed to Install on TB 63.0b1 (corrupt)

### ISSUE THREAD

**Issue by SLiNv** [Ximi1970/Manually-Sort-Folders#4]
Platform: Win10 64-bit + TB 63.0b1 + Manually Sort v1.2.0pre3

Install v1.2.0pre3 from file TB says ```This add-on could not be installed because it appears to be corrupt```. 

Error message in console:
```
NS_ERROR_FILE_NOT_FOUND:           15 ActorManagerChild.jsm:68
1540314729321	addons.xpi	WARN	Invalid XPI: Error: Non-restartless extensions no longer supported(resource://gre/modules/addons/XPIInstall.jsm:647:13) JS Stack trace: loadManifestFromRDF@XPIInstall.jsm:647:13
loadFromRDF@XPIInstall.jsm:787:23 

```

**Comment by aqtem** [comment]
TB 64.0b1 (32-bit) manual install attempt finished with the following dialog:
This addon couldn't be installed because it is not compatible with TB 64.0
Please update it to make compatible,
Great work, thank you

**Comment by Ximi1970** [comment]
Account sort is working again for 63 and 64 in the feature-bootstrap-tb64 branch.
Folder sort and startup folders still not working due to overlay removals in Thunderbird 61+.

**Comment by aqtem** [comment]
Can you please share a link where to download x64 TB ?
Thank you

**Comment by Ximi1970** [comment]
Sorry, no addon releases for Thunderbird beta. To unstable for real use...

**Comment by aqtem** [comment]
Ok, thank you for a reply, but I cannot find anywhere x64 TB stable release, is it available or it does not exist at all? TB is only x86 ?

**Comment by Ximi1970** [comment]
Oh sorry thought you wanted a precompiled addon.
If you really want to try the beta Thunderbirds (or any other version) you can find them here:

https://archive.mozilla.org/pub/thunderbird/releases/

BUT please be careful, I already lost my test config several times.....

**Comment by aqtem** [comment]
Yes, its all the versions but not an x64 bit, they are only x86 bit available for Windows, isn't it?

**Comment by Ximi1970** [comment]
You can find the english-US x64 windows version in:

 https://archive.mozilla.org/pub/thunderbird/releases/64.0b1/win64/en-US/

It is 64bit...

**Comment by aqtem** [comment]
Greatly appreciate!

**Comment by Ximi1970** [comment]
Addon is fixed for Tb 63 and Tb 64. Have a look at the feature-tb64 branch.

**Comment by aqtem** [comment]
Where to find "feature-tb64 branch" ?
Still not working on mine (

**Comment by Ximi1970** [comment]
Select the branch on the main page and download the zip file.
Or click:
https://github.com/Ximi1970/Manually-Sort-Folders/archive/feature-tb64.zip

On linux:

unzip Manually-Sort-Folders-featue-tb64.zip
cd Manually-Sort-Folders-feature-tb64
make

Install the generated xpi file with "Install add-on From file" in the Thunderbird Add-on Manager page.

----------------------------------
Or using the repostory:

On linux (packages for git and zip need to be installed):

mkdir github
cd github
git clone https://github.com/Ximi1970/Manually-Sort-Folders.git
cd Manually-Sort-Folders
git checkout feature-tb64
make

Install the generated xpi file with "Install add-on From file" in the Thunderbird Add-on Manager page.

**Comment by aqtem** [comment]
I'm on windows, cannot find any ".xpi" file within this archive

**Comment by Ximi1970** [comment]
You need to compile it yourself.
I am not going to release xpi files for beta developer Thunderbird releases.

Please use the latest stable Thunderbird version (60.3.0) if you are not willing to do any development.

**Comment by aqtem** [comment]
But how to do that via Windows os?
Thank you

**Comment by Ximi1970** [comment]
Little lesson in using Unix on Windows.

Go to the Cygwin website (https://www.cygwin.com/) and download Cygewin. You can choose 32 or 64 bit version:

32bit: https://www.cygwin.com/setup-x86.exe
64bit: https://www.cygwin.com/setup-x86_64.exe

Start installing the package:
Next
Download Source. Install from Internet. Next.
Root Install Dir. Do not change anything. Next.
Local Dir. Do not change anything. Next.
Use System Proxy Settings. Do not change anything. Next.
Choose Download Site. Select a site near you. Next.
Select Packages. Do not change anything. Next.
Next
Finish

There should now be a Cygwin Terminal icon on your desktop.
Start the terminal. First we are going to install some extra packages using the previous downloaded installer:

cd /cygdrive/c/Users/<your username>/Downloads
./setup-x86_64.exe -q -P zip,git,make,wget

Now let's get the source:

cd ../Documents
mkdir Github
cd Github
git clone https://github.com/Ximi1970/Manually-Sort-Folders.git
cd Manually-Sort-Folders
git checkout feature-tb64
make

There should be a file named: tbsortfolders.xpi in the Documents/Github/Manually-Sort-Folders directory.
Install the generated xpi file with "Install add-on From file" in the Thunderbird Add-on Manager page.
